name: vercel-deployment
on:
  workflow_run:
    workflows: ["build-and-test"]
    types:
      - completed
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  
jobs:
  production:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¦ Checkout repository
        uses: actions/checkout@v4
      
      - name: ğŸ“¥ Download and install vercel CLI
        run: npm install --global vercel@latest
        
      - name: â¬‡ï¸ Pull vercel environment information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        
      - name: ğŸ› ï¸ Build project artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
        
      - name: ğŸš€ Deploy project artifacts to vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
